const Meal = (
  title,
  id,
  primaryImageUrl,
  ingredients,
  steps,
  imageUrls,
  tags,
  rating,
  authorId,
  creationDate,
  editorId,
  editDate,
  links,
  isTestMangi,
  reactions,
) => ({
  title,
  id,
  primaryImageUrl,
  ingredients,
  steps,
  imageUrls,
  tags: tags ? tags : [],
  rating,
  authorId,
  creationDate,
  editorId,
  editDate,
  links: links ? links : [],
  isSelected: false,
  isTestMangi: isTestMangi ? isTestMangi : false,
  reactions: reactions ? reactions : [],
});

export default Meal;
